version: '3.9'
services:
  rabbitmq_server:
    hostname: 'mabbit'
    image: rabbitmq:3.8.25-management
    container_name: rabbitmq_server
    restart: always
    tty: true
    stdin_open: true
    networks:
      - jms_example
    volumes:
      - ./enable_plugins:/etc/rabbitmq/enable_plugins
      - ./data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  device_1:
    image: ivanogc99/sensor_device:1.0
    container_name: device_1
    restart: always
    environment:
      - RMQ_USER=guest
      - RMQ_PASS=guest
      - RMQ_HOST=rabbitmq_server
      - RMQ_PORT=5672
      - DEVICE_ID=1
      - SEND_RATE=3000
    networks:
      - jms_example
    depends_on:
      - rabbitmq_server

  device_2:
    image: ivanogc99/sensor_device:1.0
    container_name: device_2
    restart: always
    environment:
      - RMQ_USER=guest
      - RMQ_PASS=guest
      - RMQ_HOST=rabbitmq_server
      - RMQ_PORT=5672
      - DEVICE_ID=2
      - SEND_RATE=3000
    networks:
      - jms_example
    depends_on:
      - rabbitmq_server

  statistics:
    image: ivanogc99/statistics_device:1.0
    container_name: statistics_device
    restart: always
    environment:
      - RMQ_USER=guest
      - RMQ_PASS=guest
      - RMQ_HOST=rabbitmq_server
      - RMQ_PORT=5672
      - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - jms_example
    depends_on:
      - rabbitmq_server
      - device_1
      - device_2

volumes:
  rabbitmq_data:

networks:
  jms_example: